name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Check code formatting
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run unit tests
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build assembly JAR
        run: make build-assembly

      - name: Upload assembly artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruuvi-data-forwarder-assembly
          path: target/scala-3.*/ruuvi-data-forwarder-assembly-*.jar
          retention-days: 7

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build assembly JAR
        run: make build-assembly

      - name: Create test data
        run: |
          echo '{"battery_potential":2335,"humidity":653675,"measurement_ts_ms":1693460525701,"mac_address":[254,38,136,122,102,102],"measurement_sequence_number":53300,"movement_counter":2,"pressure":100755,"temperature_millicelsius":-29020,"tx_power":4}' > test-data.jsonl
          echo '{"battery_potential":1941,"humidity":570925,"measurement_ts_ms":1693460275133,"mac_address":[213,18,52,102,20,20],"measurement_sequence_number":559,"movement_counter":79,"pressure":100621,"temperature_millicelsius":22005,"tx_power":4}' >> test-data.jsonl

      - name: Test Console sink
        run: make test-console-sink

      - name: Test JSON Lines sink
        run: make test-jsonlines-sink

      - name: Verify output file
        run: |
          if [ -f data/telemetry.jsonl ]; then
            echo "✓ JSON Lines output file created"
            cat data/telemetry.jsonl
          else
            echo "✗ JSON Lines output file not created"
            exit 1
          fi
